- name: Add ssh key for meera
  tags: always
  authorized_key:
    user: meera
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB0gDt/0YN0E1TaSChv5RANtvuRPzspmQADDMuX5wqz+ ansible"

- name: Generate sshd_config from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd